### ISSUE TITLE
Duplicate nickname with social registration

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#115]
api/v1/auth/google:1 Failed to load resource: the server responded with a status of 504 (Gateway Time-out)

```
MongoError: E11000 duplicate key error collection: bud.users index: bio.nickname_1 dup key: { bio.nickname: "Leoš Literák" }
    at Function.create (/var/www/beta.mezinamiridici.cz/backend/node_modules/mongodb/lib/core/error.js:57:12)
    at toError (/var/www/beta.mezinamiridici.cz/backend/node_modules/mongodb/lib/utils.js:123:22)
    at /var/www/beta.mezinamiridici.cz/backend/node_modules/mongodb/lib/operations/common_functions.js:265:39
    at handler (/var/www/beta.mezinamiridici.cz/backend/node_modules/mongodb/lib/core/sdam/topology.js:942:24)
    at /var/www/beta.mezinamiridici.cz/backend/node_modules/mongodb/lib/cmap/connection_pool.js:356:13
    at handleOperationResult (/var/www/beta.mezinamiridici.cz/backend/node_modules/mongodb/lib/core/sdam/server.js:558:5)
    at MessageStream.messageHandler (/var/www/beta.mezinamiridici.cz/backend/node_modules/mongodb/lib/cmap/connection.js:275:5)
```

Source code:

```
      if (!user) {
        logger.debug('User not found');
        const userId = mongo.generateTimeId();
        await insertUser(dbClient, userId, email, name, req.params.provider);
        logger.debug('User created');
        const token = auth.createToken(userId, name, new Date(), null, false, '1m');
        return api.sendResponse(res, { access_token: token, token_type: 'bearer', email, name, userId, active: false });
      }
```

Ideally give a user chance to select his own nickname

**Comment by literakl** [comment]
added TODOs: https://github.com/literakl/mezinamiridici/tree/115-rewrite_social_registration

**Comment by literakl** [comment]
SignIn.vue:145 Auth starts facebook
SignIn.vue:151 {data: {…}, status: 200, statusText: "OK", headers: {…}, config: {…}, …}config: {url: "https://beta.mezinamiridici.cz/api/v1/auth/facebook", method: "post", data: "{"code":"AQzfk2TxCJl…s://beta.mezinamiridici.cz/api/v1/auth/facebook"}", headers: {…}, transformRequest: Array(1), …}data: {access_token: "eyJhbU3Mea7s5s", token_type: "bearer", active: true}headers: {access-control-allow-origin: "*", cache-control: "private", connection: "keep-alive", content-encoding: "gzip", content-type: "application/json; charset=utf-8", …}request: XMLHttpRequest {readyState: 4, timeout: 0, with status: 200statusText: "OK"__proto__: Object
vue.runtime.esm.js:619 [Vue warn]: Error in v-on handler (Promise/async): "TypeError: Cannot read property 'data' of undefined"
found in
---> <Button> at src/components/atoms/Button.vue
       <ValidationObserver>
         <Signin> at src/views/user/SignIn.vue
           <App> at src/App.vue
             <Root>
vue.runtime.esm.js:1888 TypeError: Cannot read property 'data' of undefined
    at VueComponent._callee2$ (user-chunk.js:2076)
Navigated to https://beta.mezinamiridici.cz/prihlaseni

**Comment by literakl** [comment]
SignIn.vue:145 Auth starts facebook
SignIn.vue:147 Already authenticated
_callee2$ @ user-chunk.js:2041
SignIn.vue:151 {data: {…}, status: 200, statusText: "OK", headers: {…}, config: {…}, …}config: {url: "https://beta.mezinamiridici.cz/api/v1/auth/facebook", method: "post", data: "{"code":"AQDBE
vue.runtime.esm.js:619 [Vue warn]: Error in v-on handler (Promise/async): "TypeError: Cannot read property 'data' of undefined"
found in
---> <Button> at src/components/atoms/Button.vue
       <ValidationObserver>
         <Signin> at src/views/user/SignIn.vue
           <App> at src/App.vue
             <Root>
vue.runtime.esm.js:1888 TypeError: Cannot read property 'data' of undefined
    at VueComponent._callee2$ (user-chunk.js:2076)

**Comment by literakl** [comment]
2020-12-21 20:52:42:790[verbose]: Facebook authentication starts
2020-12-21 20:52:42:927[verbose]: socialAction starts
2020-12-21 20:52:42:927[debug]: Connect to mongo database
2020-12-21 20:52:42:928[debug]: Using cached database instance
2020-12-21 20:52:42:928[debug]: Mongo connected
2020-12-21 20:56:01:534[verbose]: socialLink GET handler starts
2020-12-21 20:56:01:535[info]: {
  code = AQDeDg
}
2020-12-21 20:56:01:793[verbose]: socialLink POST handler starts
2020-12-21 20:56:01:794[info]: {
  code = AQDFeDg
  clientId = 860316561127732
  redirectUri = https://beta.mezinamiridici.cz/api/v1/auth/facebook
}
2020-12-21 20:56:01:794[verbose]: Facebook authentication starts
2020-12-21 20:56:01:939[verbose]: socialAction starts
2020-12-21 20:56:01:940[debug]: Connect to mongo database
2020-12-21 20:56:01:940[debug]: Using cached database instance
2020-12-21 20:56:01:940[debug]: Mongo connected
2020-12-21 20:56:01:946[debug]: User not found, store socialId
2020-12-21 20:56:01:961[debug]: SocialId created

**Comment by literakl** [comment]
finished, user can choose nickname even when signing with a social network. The flow of email/social signup is unified now.
