### ISSUE TITLE
Replace Winston logging with log4js node

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#157]
https://github.com/log4js-node/log4js-node

- Update logging.js - provide a facade for Winston API, so we do not need to patch every single logging occurence
- There should be one app logger across the source code and one mongo CSV logger used in mongo.js only (#134).
- Prepare an external configuration file for backend. It is OK that its modification would require a server reload. Setup a daily rolling policy for standard app logger.
- Create configuration file(s) for each CLI job. Setup a size based rolling policy (e.g. over 1 MB).
- Create new reconfigure method that takes a file name as a property, loads the configuration file and updates app logger configuration
- No hard coded paths in the source code. Use env variables. Remember to set a default value in `.env.template`.

Related issues to solve:

- [x] #148 
- [ ] #96 

Tests:

- [x] restart will continue in the same log and will not override the existing data
- [ ] rollover will create new file and the previous file is preserved regarding the keep policy

**Comment by literakl** [comment]
ok

**Comment by literakl** [comment]
Error: Cannot find module '/var/www/beta.mezinamiridici.cz/backend/src/utils/var/www/beta.mezinamiridici.cz/backend/config/logger.js'
Require stack:
- /var/www/beta.mezinamiridici.cz/backend/src/utils/logging.js
- /var/www/beta.mezinamiridici.cz/backend/src/utils/api.js
- /var/www/beta.mezinamiridici.cz/backend/src/handlers/getStatus.js
- /var/www/beta.mezinamiridici.cz/backend/src/server.js
- /var/www/beta.mezinamiridici.cz/backend/src/start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
    at require (internal/modules/cjs/helpers.js:74:18)
    at configureLoggers (/var/www/beta.mezinamiridici.cz/backend/src/utils/logging.js:51:24)
    at Object.<anonymous> (/var/www/beta.mezinamiridici.cz/backend/src/utils/logging.js:111:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/beta.mezinamiridici.cz/backend/src/utils/logging.js',
    '/var/www/beta.mezinamiridici.cz/backend/src/utils/api.js',
    '/var/www/beta.mezinamiridici.cz/backend/src/handlers/getStatus.js',
    '/var/www/beta.mezinamiridici.cz/backend/src/server.js',
    '/var/www/beta.mezinamiridici.cz/backend/src/start.js'
  ]
}

CONFIG_DIRECTORY=/var/www/beta.mezinamiridici.cz/backend/config
LOG_DIRECTORY=/var/www/beta.mezinamiridici.cz/backend/logs

**Comment by literakl** [comment]
It seems that only relative paths are supported. We already use the absolute paths:

TEMPLATES_DIRECTORY=/var/www/beta.mezinamiridici.cz/backend/templates
BLOG_PICTURES_UPLOAD_DIR=/var/www/beta.mezinamiridici.cz/html/images/upload
STREAM_PICTURES_DIR=/var/www/beta.mezinamiridici.cz/html/images/stream

I assume that there will be some difference how path module is used in logging.js

**Comment by literakl** [comment]
fixed
