### ISSUE TITLE
Parse accidents dies on a server

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#231]
```
TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor.prototype" property must be of type object. Received undefined
    at Object.inherits (util.js:160:11)
    at Object.exports.wrap (/var/www/beta.mezinamiridici.cz/backend/node_modules/cheerio-advanced-selectors/index.js:20:8)
    at Object.<anonymous> (/var/www/beta.mezinamiridici.cz/backend/src/jobs/parseAccidents.js:23:34)
```

**Comment by literakl** [comment]
Probably incompatibility with the latest Cheerios

https://github.com/cheeriojs/cheerio/discussions/2121
