### ISSUE TITLE
Log stack trace and object

### ISSUE THREAD

**Issue by literakl** [literakl/mezinamiridici#97]
https://stackoverflow.com/a/53414984/1639556

logger.error('failing', { error: err });

Find all occurences all logger.error() and add the error. 

Use the same pattern for objects to be logged. This check can be removed then.

const myFormat = printf(info => `${info.timestamp} [${info.level}]: ${info.message === Object(info.message) ? stringify(info.message) : info.message}`);

**Comment by literakl** [comment]
I want to achieve that the log will contain the error message, error description and the stacktrace to isolate it. I need a timestamp too. It would be nice to log current URL and HTTP method as well.

**Comment by literakl** [comment]
This code

`        throw new Error('XSS detected');`

results in

2021-04-18 13:29:12.377 [ERROR] [test]: Request failed Error: XSS detected
    at filter (C:\dev\mezinamiridici\backend\src\handlers\users\updateUser.js:87:15)
    at Array.filter (<anonymous>)
    at prepareUpdateProfileQuery (C:\dev\mezinamiridici\backend\src\handlers\users\updateUser.js:81:32)
    at C:\dev\mezinamiridici\backend\src\handlers\users\updateUser.js:19:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

So the code works for unhandled errors.
